# -*- coding: utf-8 -*-
"""Count number of Faces using Python - OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJW4aEUFCsDUhg_YUKIZjOwVqhlXiIks
"""

from IPython.display import display, Javascript
from google.colab.output import eval_js
import cv2
import numpy as np
from base64 import b64decode

def capture_image():
    js = Javascript('''
        async function capture() {
            const video = document.createElement('video');
            video.style.position = 'fixed';
            video.style.top = '0';
            video.style.left = '0';
            video.style.width = '320px';
            video.style.height = '240px';
            video.style.zIndex = '9999';
            document.body.appendChild(video);

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            video.srcObject = stream;
            await video.play();

            await new Promise(resolve => setTimeout(resolve, 2000));

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);

            stream.getTracks().forEach(t => t.stop());
            video.remove();

            return canvas.toDataURL('image/jpeg');
        }
    ''')
    display(js)
    img_data = eval_js("capture()")
    img_bytes = b64decode(img_data.split(',')[1])
    img_array = np.frombuffer(img_bytes, dtype=np.uint8)
    return cv2.imdecode(img_array, cv2.IMREAD_COLOR)

import dlib

detector = dlib.get_frontal_face_detector()

img = capture_image()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = detector(gray)

print("Faces detected:", len(faces))

for face in faces:
    x, y = face.left(), face.top()
    x1, y1 = face.right(), face.bottom()
    cv2.rectangle(img, (x,y), (x1,y1), (0,255,0), 2)

from google.colab.patches import cv2_imshow
cv2_imshow(img)